# Generated by Django 4.1 on 2024-07-01 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TimeMachineApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='portfolio_site',
            new_name='personal_site',
        ),
        migrations.RenameField(
            model_name='userprofileinfo',
            old_name='profile_pic',
            new_name='profile_image',
        ),
    ]
